### PR TITLE
Remove hardcoded xvfb

### PR DESCRIPTION
**Pull request by Miffyli**
Remove hardcoded xvfb use on Linux, which can speed up MineRL by 2-3x on headed, GPU machines. Also update docs to reflect the new behaviour (e.g. the Minecraft window does not update while agent plays).

You can also use `MINERL_HEADLESS=1` to do headless runs (adds xvfb automatically).

### CODE REVIEW

**Review by brandonhoughton — APPROVED** [review]
Lgtm!

**Comment by Miffyli** [comment]
Are the CI/build errors something related to these changes or random derp? I can not see the logs.
Maybe CI requires adding the MINERL_HEADLESS thing?
Locally docs and MineRL works fine.

**Review by brandonhoughton — APPROVED** [review]

**Comment by brandonhoughton** [comment]
ERROR: /var/lib/buildkite-agent/builds/buildkite-root-20210629101407-19-1/openai-mono/minerl-public-dev/pytest.ini:11: duplicate name 'setenv'

**Comment by Miffyli** [comment]
Gah, it would be nice to fix the errors if it is related to the headless-ness. Was it the pytest config again? :')

**Comment by shwang** [comment]
We can probably get CircleCI (i.e. public testing failure logs) up for tests that don't launch Minecraft soon.

(The current tests that launch Minecraft are flakey anyways, because BASALT envs (maybe even all environments) have some random spawn deaths for some reason)

**Comment by Miffyli** [comment]
Gotcha, I am going to merge this as this feature would be very desirable for v0.4.1, and it passes locally.

**Pull request merged**
