### PR TITLE
MVP Basalt env Sphinx docs

### PR DESCRIPTION
**Pull request by shwang**
Merge #510 first.

Some basic Basalt environment docs.

Includes a macro for generating starting inventory Sphinx docs inserts (This is important
for several BASALT tasks). Adds docs/README.md for doc generation and viewing quickstart.

Removes a few Sphinx build warnings by having the heading delimiters ("......") be the same
length as the headings.

- docs/README.md: Add brief README for quickstart
- Basic basalt docs

### CODE REVIEW

**Comment by shwang** [comment]
Docs and TOC now looks like this:

image


We will need to find a better TOC hierarchy for diamond vs. basalt environments later.

**Comment by shwang** [comment]
(Rebased onto `dev` after squash-merging #510)

**Review by brandonhoughton — APPROVED** [review]

**Comment by Miffyli** [comment]
@shwang 

Small issue: Windows does not allow `:` in filenames (e.g. `docs/source/assets/basalt/waterfall8_0:30.gif` is invalid path). Can you update the filenames to use e.g. `-` instead?

**Comment by shwang** [comment]
Sure — out of curiosity what happens to windows machine when it tries to
download this file? 😂

**Comment by Miffyli** [comment]
She just throws her usual hissy-fit and pretends it is not there :') 

image

Edit: I guess this can be better than having some obscure, non-renderable control characters as filenames in Unix when you accidentally press one too many buttons, and then you are stuck with a file that requires Unix-Magic lvl 45 to access, let alone delete.

**Pull request merged**
