### PR TITLE
Fixed XML_template issue

### PR DESCRIPTION
**Pull request by mchoccie**
Small fix for anyone who wants to experiment by creating custom environments. I noticed this function name was off, so I fixed it. Let me know what you think.

### CODE REVIEW

**Comment by Miffyli** [comment]
Hey! Could consider merging this, if you could add more description on:

- What was the original issue
- How this fixes it / what it fixes, or what it enables
- Examples of behaviour before and after the fix (including the code/method to test it myself too)

**Comment by mchoccie** [comment]
@Miffyli Sure thing, I can provide those details

**Review by Miffyli — APPROVED** [review]
Lol a quick search figured out that indeed this was a typo, and no other results of  `xml_element` exist anywhere else. Merging :). Thanks for going through the effort!

**Comment by mchoccie** [comment]
@Miffyli thank you for merging! Apologies, I was going to add a proper write up of what the bug fixes, however I got a bit caught up working on a Minerl project.

**Pull request merged**
