### PR TITLE
Fix and refactor Sphinx EnvSpec docs

### PR DESCRIPTION
**Pull request by shwang**
Refactors logic in Sphinx docs, minor linting, and fixes a couple of errors
using a refactored EnvSpec-to-Sphinx function.

- docs: remove trailing white-space
- docs: Fix NameError due to past-deprecated fn
- docs: Add EnvSpec-to-Sphinx utility and smoke test
- docs../environments: Fix broken env descriptions

### CODE REVIEW

**Comment by shwang** [comment]
Previously: 
image

**Comment by shwang** [comment]
Now:
image

**Comment by shwang** [comment]
Seems to pass tests locally via `pytest`. When you get a chance, let me know what's going in BuildKite! @brandonhoughton

**Comment by brandonhoughton** [comment]
Probably just a rebase issue

**Comment by brandonhoughton** [comment]
image

**Review by brandonhoughton — APPROVED** [review]

**Pull request merged**
